#!/usr/bin/env python3
import re, sys

DATA = {
 1: "LSLSSLSLSLSLSLSLSLSLSLSGLSLSSLSLSLLSLSLSLSLSLSLGLSLSSLSLSLSLSLSLLSSLSLSGLSLSSLSLSLSLSLSLLSSLSLSGLSLSSLSLSLSLSLSLLSSLSLSGLSLSSLSLSLSLSLSLLSSLSLSGLSLSSLSLSLSLSLSLLSSLSLSGLSLSSLSLSLSLSLSLLSSLSLSGLSLSSLSLSLSLSLSLLSSLSLSGLSLSSLSLSLSLSLSLLSSLSLS",
 2: "LSLSSLSLSLSLSLSLSLSLSLSGLSLSSLSLSLLSLSLSLSLSLSLGLSLSSLSLSLSLLSSLSLSLSLSGLSLSSLSLSLSLLSSLSLSLSLSGLSLSSLSLSLSLLSSLSLSLSLSGLSLSSLSLSLSLLSSLSLSLSLSGLSLSSLSLSLSLLSSLSLSLSLSGLSLSSLSLSLSLLSSLSLSLSLSGLSLSSLSLSLSLLSSLSLSLSLSGLSLSSLSLSLSLLSSLSLSLSLS",
 3: "LSLSSLSLSLSLSLSLSLSLSLSGLSLSSLSLSLLSLSLSLSLSLSLGLSLSSLSLSLSLSLSLSLSLSLLGLSLSSLSLSLSLSLSLSLSLSLLGLSLSSLSLSLSLSLSLSLSLSLLGLSLSSLSLSLSLSLSLSLSLSLLGLSLSSLSLSLSLSLSLSLSLSLLGLSLSSLSLSLSLSLSLSLSLSLLGLSLSSLSLSLSLSLSLSLSLSLLGLSLSSLSLSLSLSLSLSLSLSLLGLSLSSLSLSLSLSLSLSLSLSLLGLSLSSLSLSLSLSLSLSLSLSLL",
 4: "LSLSSLSLSLSLSLSLSLSLSLSGLSLSSLSLSLLSLSLSLSLSLSLGLSLSSLSLSLSLSLSLSLLSSLSGLSLSSLSLSLSLSLSLSLLSSLSGLSLSSLSLSLSLSLSLSLLSSLSGLSLSSLSLSLSLSLSLSLLSSLS",
 5: "LSLSSLSLSLSLSLSLSLSLSLSGLSLSSLSLSLLSLSLSLSLSLSLGLSLSSLSLSLLSSLSLSLSLLSLGLSLSSLSLSLLSSLSLSLSLLSL",
 6: "LSLSSLSLSLSLSLSLSLSLSLSGLSLSSLSLSLLSLSLSLSLSLSLGLSLSSLSLSLSLSLSLSLLSSLSGLSLSSLSLSLSLSLSLSLLSSLSGLSLSSLSLSLSLSLSLSLLSSLSGLSLSSLSLSLSLSLSLSLLSSLSGLSLSSLSLSLSLSLSLSLLSSLSGLSLSSLSLSLSLSLSLSLLSSLSGLSLSSLSLSLSLSLSLSLLSSLS",
}

def decode_frame(s23):
    # s23: 23 chars of S/L (no G)
    bits = []
    for i in range(0, 21, 2):
        mark = s23[i]
        space = s23[i + 1]
        if mark == 'L' and space == 'S':
            bits.append('1')
        elif mark == 'S' and space == 'L':
            bits.append('0')
        else:
            bits.append('?')
    # element index 22 (0-based) is the trailing mark -> bit 12
    trail = s23[22]
    bits.append('0' if trail == 'S' else '1')
    return ''.join(bits)

for btn in sorted(DATA):
    s = DATA[btn]
    # split into frames: 23 chars then optional G
    frames = re.findall(r'[SL]{23}G?', s)
    print(f'=== boton {btn} ===')
    seen = []
    for f in frames:
        core = f[:23]
        bits = decode_frame(core)
        gap = 'G' if len(f) == 24 else '-'
        seen.append(bits)
        print(f'  {bits}  gap={gap}')
    # summarize unique
    uniq = []
    for b in seen:
        if b not in uniq:
            uniq.append(b)
    print(f'  UNICOS: {uniq}')
